name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: yarn install
      - name: lint
        run: yarn run lint
      - name: type check
        run: yarn run type-check
      - name: test
        run: yarn test
